### ISSUE TITLE
Doesn't work well with locally-deployed charms

### ISSUE THREAD

**Issue by AdamIsrael** [niedbalski/juju-deployerizer#6]
With charms deployed from a local repository, such as an in-development or proprietary charm, the resulting bundle file points to the charm store, i.e., a charm deployed from local:trusty/mycharm points to cs:trusty/mycharm in the bundle.

**Comment by niedbalski** [comment]
@AdamIsrael there is a parameter '--charm-location-format=local, cs' that allows you to specify the prefix used by the charms. I fixed this , now by default will print out the corresponding charm prefix without modification.

Thanks for reporting!

**Comment by niedbalski** [comment]
The fix is uploaded into pip / github. 

Thanks.

**Comment by lazypower** [comment]
:+1: Awesome @niedbalski  thanks for the quick turn around
